# Generated by Django 2.2.1 on 2020-07-04 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('direccion', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
            ],
            options={
                'db_table': 'Example1',
            },
        ),
    ]
