# Generated by Django 2.2.1 on 2020-07-04 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
