# Generated by Django 2.2.1 on 2020-07-04 03:17

import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200703_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default='(0,100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
