# Generated by Django 2.2.1 on 2020-07-04 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0005_auto_20200703_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
